services:
  redis:
    container_name: chat-redis
    image: redis
    ports:
      - "6379:6379"

  postgres:
    container_name: chat-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_MAX_CONNECTIONS: 100
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node:
    container_name: chat-node
    build:
      context: frontend/docker/development/node
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    tty: true

  backend:
    container_name: chat-go
    build:
      context: backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOSTS: postgres
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v6
    volumes:
      - ./centrifugo:/centrifugo
    command: centrifugo -c config.json
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  postgres_data:
